# .github/workflows/daily-call.yml
name: Daily API Call - PVP

on:
  schedule:
    - cron: '0 6 * * *' # 6h UTC todos os dias
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Chama a API do PVP em Railway
        run: curl -X GET https://fundsexplorer-production.up.railway.app/pvp
